pkglist=(
abusaidm.html-snippets
alefragnani.Bookmarks
alexdima.copy-relative-path
anseki.vscode-color
Arjun.swagger-viewer
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
chrmarti.regex
codezombiech.gitignore
CoenraadS.bracket-pair-colorizer-2
Dart-Code.dart-code
Dart-Code.flutter
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
EditorConfig.EditorConfig
eg2.tslint
eg2.vscode-npm-script
esbenp.prettier-vscode
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
freakone.cursoruler
gio00.fish
GitHub.vscode-pull-request-github
gizak.shortcuts
GrapeCity.gc-excelviewer
Gruntfuggly.todo-tree
hollowtree.vue-snippets
HookyQR.beautify
humao.rest-client
JamesBirtles.svelte-vscode
joelday.docthis
mrmlnc.vscode-doiuse
ms-azuretools.vscode-docker
MS-CEINTL.vscode-language-pack-ja
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-ssh-explorer
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.Go
ms-vscode.vscode-typescript-tslint-plugin
msjsdiag.debugger-for-chrome
octref.vetur
oderwat.indent-rainbow
oysun.vuehelper
PKief.material-icon-theme
prograhammer.tslint-vue
rubbersheep.gi
ryu1kn.annotator
shardulm94.trailing-spaces
spywhere.guides
stevencl.addDocComments
Tyriar.sort-lines
VisualStudioExptTeam.vscodeintellicode
wmaurer.change-case
wmaurer.vscode-jumpy
Zignd.html-css-class-completion
)

for i in ${pkglist[@]}; do
  code --install-extension $i
done

sudo cp -f ./settings.json ~/Library/Application\ Support/Code/User/settings.json
